[package]
name = "basic"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
scylla = { version = "0.4.7" }
tokio = { version = "1.12", features = ["full"] }
getopts = "0.2.12"
anyhow = "1.0.40"

[profile.release]
lto = true